BASE_DIRECTORY: 'train_out'
EXPERIMENT_NAME: 'sup_16k_rigidAug1-2'
NUM_WORKERS: 8
USE_AMP: False
DEVICE: 'cuda'
MODEL:
  PPWC_SFPC_BN: False
SOLVER:
  BATCH_SIZE: 4
  NUM_EPOCHS: 1500
  LEARNING_RATE: 0.001
  SCHEDULER: 'multistep'
  LR_LAMBDA: 0.1
  LR_MILESTONES: [1200,1400]
  LOSS_FACTOR: 10.
INPUT:
  SCALE_NORM_FACTOR: 100
AUGMENTATIONS:
  METHOD: 'rigid_one'
  MAX_ROTATION_ANGLE: 10.
  MAX_SCALE_OFFSET: 0.1
  MAX_TRANSLATION: 0.005